### ISSUE TITLE
Injection custom headers

### ISSUE THREAD

**Issue by jicho** [SkullTech/drymail#3]
Hi,

When I add headers with:
```
msg = Message(headers=headers)
```

They are not added to the message that is created. Am I doing something wrong, or... should I use:
```
msg.message.add_header('test', 'hi')
```

The add_header works, but I think it's a bit weird to use it when there is a headers parameter :)

I've tried adding the header with a list of string, and also as tuple, but both do not end up in the final message...

For now I will use the add_headers. Was just wondering if I was doing something strange when using the headers param.

Thanks for the reaction.

**Comment by skulltech** [comment]
Fixed in the latest version 0.0.6. Thanks for pointing it out.

**Comment by gunslinger** [comment]
I think this still not working. can you do some test again?

**Comment by skulltech** [comment]
@gunslinger I just checked and it is working. Maybe you're not using the latest version? You can check which version of the library using using the following command

```console
(venv) sumit@HAL9000:~$ pip3 show drymail
Name: drymail
Version: 0.0.6
Summary: Drymail is a minimalist wrapper over Python’s existing smtplib and email libraries, designed to be friendly but unrestrictive. 
Home-page: https://github.com/SkullTech/drymail
Author: Sumit Ghosh
Author-email: sumit@sumit-ghosh.com
License: MIT
Location: /home/sumit/Coding/drymail/venv/lib/python3.7/site-packages
Requires: mistune, beautifulsoup4
Required-by: 
```
It should show version `0.0.6`

**Comment by jicho** [comment]
I can also confirm that version 0.0.6 fixes the problem.

Bit late test/upgrade/reaction :(

@SkullTech: Thanks for fixing this.

**Comment by skulltech** [comment]
Sorry for being late. I have to work on this, my response time :) Anyway glad that it helped you. Cheers!!
