### ISSUE TITLE
Attachment shows before text in thunderbird

### ISSUE THREAD

**Issue by s-n-g** [SkullTech/drymail#4]
Hi

I have just tried drymail and I think it's fantastic!
Thank you for this!

I just encountered an "issue" with email presentation on thunderbird: the attachment (in this case a jpg) is shown before the actual text of the message.

I have checked with gmail and yahoo web interface; everything ok there, but I guess they do their own reformatting...

I have inspected the code of the message received and noticed that the attachment is actually placed before the text.

Would it be the cause?
Would placing the attachment(s) at the end of the message "fix" this?
Or is it just a thunderbird thing and I should contact them instead?

Thanks,
Spiros

EDIT--------------------------------
I can confirm this is the case.
I have edited the code of the message, placed the text part (both plain and html) before the attachment, and used *prepared_message* for **Message**
Thunderbird is happy now :)

If only I could do that in python and provide a PR... :(

**Comment by s-n-g** [comment]
I have made a complete mess of it, I know :)
But I think the PR that is still open is a solution to the problem

Spiros

**Comment by skulltech** [comment]
I see. This is a real issue, I don't use Thunderbird myself so I didn't notice it. I'll take a look at your PR shortly. Thanks!!

**Comment by s-n-g** [comment]
Closing this one since https://github.com/SkullTech/drymail/pull/8 accepted and merged
